version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: html5_css_javascript_programing
    ports: 
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
